#!/usr/bin/env bash

set -o errexit

function _print_usage
{
    printf "Usage: %s [--extract] PATHNAME\n" "$(basename "$0")"
}

function _exit
{
    _print_usage

    exit 0
}

function _exit_error
{
    _print_usage >&2

    exit 1
}

function _main
{
    local target
    local should_extract

    if [[ $# -eq 0 || $# -gt 2 ]]; then
        _exit_error
    fi

    if [[ $# -eq 1 ]]; then
        if [[ $1 == -h || $1 == --help ]]; then
            _exit
        fi
    else
        if [[ $1 != --extract ]]; then
            _exit_error
        fi

        should_extract=true

        shift
    fi

    target=$1

    if [[ $(uname -s) == Darwin ]]; then
        if [[ $should_extract == true ]]; then
            dsymutil --minimize -o "$target.dSYM" "$target"
        fi

        strip -r -x "$target"
    else
        if [[ $should_extract == true ]]; then
            objcopy --only-keep-debug "$target" "$target.debug"
            objcopy --strip-unneeded "$target"
            objcopy --add-gnu-debuglink="$target.debug" "$target"
        else
            objcopy --strip-unneeded "$target"
        fi
    fi
}

_main "$@"
