{% set version = '0.9.0' %}

{% if version.endswith('.dev') %}
    {% set version = version + os.getenv('MLIO_BUILD_NUMBER', '0') %}
{% endif %}

package:
  name: mlio
  version: {{ version }}

source:
  path: ../../..

build:
  number: 0
  # We do not support Windows.
  skip: True  # [not unix]

outputs:
  - name: libmlio
    script: build-mlio.sh
    build:
      run_exports:
        # We guarantee ABI compatibility only in minor versions during
        # the pre-1.0 phase.
        - {{ pin_subpackage('libmlio', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - doxygen
        - ninja
      host:
        - aws-sdk-cpp
        - libiconv
        - libopencv
        - libprotobuf
        - tbb-devel
        - zlib
    test:
      commands:
        - test -f "$PREFIX/lib/libmlio.so"     # [linux]
        - test -f "$PREFIX/lib/libmlio.dylib"  # [osx]
    about:
      summary: MLIO C++ Runtime Library

  - name: libmlio-devel
    script: build-mlio-devel.sh
    build:
      run_exports:
        # We guarantee ABI compatibility only in minor versions during
        # the pre-1.0 phase.
        - {{ pin_subpackage('libmlio', max_pin='x.x') }}
    requirements:
      build:
        - cmake
      run:
        # The development artifacts are valid only for the exact version
        # of libmlio.
        - {{ pin_subpackage('libmlio', exact=True) }}
    test:
      commands:
        - test -f "$PREFIX/include/mlio.h"  # [unix]
    about:
      summary: MLIO C++ Header Files and Development Artifacts

  - name: libmlio-dbg
    script: build-mlio-dbg.sh
    build:
      run_exports:
        # We guarantee ABI compatibility only in minor versions during
        # the pre-1.0 phase.
        - {{ pin_subpackage('libmlio', max_pin='x.x') }}
    requirements:
      run:
        # The development artifacts are valid only for the exact version
        # of libmlio.
        - {{ pin_subpackage('libmlio', exact=True) }}
    about:
      summary: MLIO Debug Symbols

  - name: mlio-py
    script: build-mlio-py.sh
    build:
      ignore_run_exports:
        # Apache Arrow is an optional component, so we avoid putting it
        # to the 'run' closure.
        - arrow-cpp
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - arrow-cpp
        - pip
        - python {{ python }}
        - setuptools
        - {{ pin_subpackage('libmlio-devel', exact=True) }}
      run:
        - numpy
        - python
        # Conda subpackages residing in the same recipe do not check the
        # run_exports directive; therefore we need to duplicate the
        # runtime constraint of libmlio here.
        - {{ pin_subpackage('libmlio', max_pin='x.x') }}
      run_constrained:
        - arrow-cpp
    test:
      imports:
        - mlio
        - mlio.integ.arrow
      requires:
        - {{ pin_compatible('arrow-cpp', exact=True) }}
    about:
      summary: MLIO Python Package

about:
  home: http://github.com/awslabs/ml-io
  license: Apache-2.0
  license_family: Apache
  summary: A high performance data access library for machine learning tasks

extra:
  recipe-maintainers:
    - cbalioglu
